# Generated by Django 5.0.2 on 2025-03-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('pet_type', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('bird', 'Птица'), ('reptile', 'Рептилия'), ('other', 'Другое')], max_length=20, verbose_name='Тип питомца')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Порода')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unknown', 'Неизвестно')], default='unknown', max_length=10, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес (кг)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VetPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=50, unique=True, verbose_name='Номер паспорта')),
                ('chip_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер чипа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ветпаспорт',
                'verbose_name_plural': 'Ветпаспорта',
            },
        ),
    ]
