# Generated by Django 5.0.2 on 2025-03-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('pet_type', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('bird', 'Птица'), ('other', 'Другое')], max_length=10, verbose_name='Тип животного')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес (кг)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вакцины')),
                ('date', models.DateField(verbose_name='Дата вакцинации')),
                ('next_date', models.DateField(verbose_name='Следующая вакцинация')),
            ],
            options={
                'verbose_name': 'Вакцинация',
                'verbose_name_plural': 'Вакцинации',
            },
        ),
        migrations.CreateModel(
            name='VetPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=50, unique=True, verbose_name='Номер паспорта')),
                ('chip_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер чипа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ветпаспорт',
                'verbose_name_plural': 'Ветпаспорта',
            },
        ),
    ]
