# Generated by Django 5.0.2 on 2025-03-23 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_initial'),
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.vet', verbose_name='Ветеринар'),
        ),
        migrations.AddField(
            model_name='vetpassport',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='passport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.vetpassport'),
        ),
    ]
