# Generated by Django 5.0.2 on 2025-03-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_delete_vetrecord'),
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pets/thumbnails/', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/photos/', verbose_name='Фото питомца'),
        ),
        migrations.CreateModel(
            name='VetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата записи')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('document', models.FileField(blank=True, null=True, upload_to='records/documents/', verbose_name='Документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='clinics.vetclinic', verbose_name='Клиника')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='pets.pet', verbose_name='Питомец')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='clinics.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Ветеринарная запись',
                'verbose_name_plural': 'Ветеринарные записи',
                'ordering': ['-date'],
            },
        ),
    ]
