# Generated by Django 5.0.2 on 2025-03-23 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteclinic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_clinics', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_services', to='clinics.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='favoriteclinic',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_clinics', to='clinics.vetclinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_services', to='clinics.vetclinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='vetrecord',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_records', to='clinics.vetclinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='vetrecord',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_records', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AddField(
            model_name='vetrecord',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_records', to='clinics.service', verbose_name='Услуга'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteclinic',
            unique_together={('user', 'clinic')},
        ),
        migrations.AlterUniqueTogether(
            name='clinicservice',
            unique_together={('clinic', 'service')},
        ),
    ]
