# Generated by Django 5.0.2 on 2025-03-23 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_initial'),
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetclinic',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vetclinic',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='clinicservice',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.vetclinic', verbose_name='Клиника'),
        ),
        migrations.AlterField(
            model_name='clinicservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='favoriteclinic',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='clinics.vetclinic', verbose_name='Клиника'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='vetclinic',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='vetrecord',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.vetclinic', verbose_name='Клиника'),
        ),
        migrations.AlterField(
            model_name='vetrecord',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AlterField(
            model_name='vetrecord',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.service', verbose_name='Услуга'),
        ),
    ]
